In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


 1. Create Two numpy array of size 3 X 2 and 2 X 3
 2.  Randomly Initalize that array


In [6]:
numpy_arr1=np.random.randint(100,size=(3,2))
numpy_arr2=np.random.randint(100,size=(2,3))
print(numpy_arr1)
print(numpy_arr2)


[[19 34]
 [99 56]
 [30  6]]
[[17 45 14]
 [57 99 45]]


# Perform matrix multiplication

In [9]:
multiplication= np.matmul(numpy_arr1,numpy_arr2)
print(multiplication)

[[2261 4221 1796]
 [4875 9999 3906]
 [ 852 1944  690]]


# Perform elementwise matrix multiplication

In [15]:
ans=np.zeros((len(numpy_arr1),len(numpy_arr2[0])))
# print(ans)
for i in range(len(numpy_arr1)):
   for j in range(len(numpy_arr2[0])):
       for k in range(len(numpy_arr2)):
           ans[i][j] += numpy_arr1[i][k] * numpy_arr2[k][j]

print(ans)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2261. 4221. 1796.]
 [4875. 9999. 3906.]
 [ 852. 1944.  690.]]


 Find mean of first matrix


In [18]:
matrix_mean=np.mean(numpy_arr1)
print(matrix_mean)

40.666666666666664


# Convert Numeric entries(columns) of mtcars.csv to Mean Centered Version

In [25]:
data=pd.read_csv('./mtcars.csv')
column_name=['mpg','cyl','disp','hp','drat','wt','qsec','vs','am','gear','carb']
for i in column_name:
  print("-----------------",i,"------------------")
  arr1=np.array(data[i])
  npcentered=arr1-np.mean(arr1)
  print(npcentered)

----------------- mpg ------------------
[ 0.909375  0.909375  2.709375  1.309375 -1.390625 -1.990625 -5.790625
  4.309375  2.709375 -0.890625 -2.290625 -3.690625 -2.790625 -4.890625
 -9.690625 -9.690625 -5.390625 12.309375 10.309375 13.809375  1.409375
 -4.590625 -4.890625 -6.790625 -0.890625  7.209375  5.909375 10.309375
 -4.290625 -0.390625 -5.090625  1.309375]
----------------- cyl ------------------
[-0.1875 -0.1875 -2.1875 -0.1875  1.8125 -0.1875  1.8125 -2.1875 -2.1875
 -0.1875 -0.1875  1.8125  1.8125  1.8125  1.8125  1.8125  1.8125 -2.1875
 -2.1875 -2.1875 -2.1875  1.8125  1.8125  1.8125  1.8125 -2.1875 -2.1875
 -2.1875  1.8125 -0.1875  1.8125 -2.1875]
----------------- disp ------------------
[ -70.721875  -70.721875 -122.721875   27.278125  129.278125   -5.721875
  129.278125  -84.021875  -89.921875  -63.121875  -63.121875   45.078125
   45.078125   45.078125  241.278125  229.278125  209.278125 -152.021875
 -155.021875 -159.621875 -110.621875   87.278125   73.278125  119.2781

In [ ]:
print(data)


             Unnamed: 0   mpg  cyl   disp   hp  ...   qsec  vs  am  gear  carb
0             Mazda RX4  21.0    6  160.0  110  ...  16.46   0   1     4     4
1         Mazda RX4 Wag  21.0    6  160.0  110  ...  17.02   0   1     4     4
2            Datsun 710  22.8    4  108.0   93  ...  18.61   1   1     4     1
3        Hornet 4 Drive  21.4    6  258.0  110  ...  19.44   1   0     3     1
4     Hornet Sportabout  18.7    8  360.0  175  ...  17.02   0   0     3     2
5               Valiant  18.1    6  225.0  105  ...  20.22   1   0     3     1
6            Duster 360  14.3    8  360.0  245  ...  15.84   0   0     3     4
7             Merc 240D  24.4    4  146.7   62  ...  20.00   1   0     4     2
8              Merc 230  22.8    4  140.8   95  ...  22.90   1   0     4     2
9              Merc 280  19.2    6  167.6  123  ...  18.30   1   0     4     4
10            Merc 280C  17.8    6  167.6  123  ...  18.90   1   0     4     4
11           Merc 450SE  16.4    8  275.8  180  ... 