In [25]:
import numpy as np
import tensorflow as tf

In [26]:
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70],[73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70]], dtype='float64')

targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], 
                    [103, 119],[56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float64')

In [27]:
inputs=tf.Variable(inputs)
targets=tf.Variable(targets)
print("Targets : \n",targets)
print("input : \n",inputs)


Targets : 
 <tf.Variable 'Variable:0' shape=(15, 2) dtype=float64, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]])>
input : 
 <tf.Variable 'Variable:0' shape=(15, 3) dtype=float64, numpy=
array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.],
       [ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.],
       [ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]])>


In [28]:
v = np.random.rand(3,2)
r = np.random.randn(2)
v = tf.Variable(v)
r = tf.Variable(r)
print(v)
print("\n",r)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=float64, numpy=
array([[0.47408266, 0.00683365],
       [0.09374311, 0.93443178],
       [0.04749622, 0.64637436]])>

 <tf.Variable 'Variable:0' shape=(2,) dtype=float64, numpy=array([-0.69863591, -1.03094384])>


In [29]:
def model(s):
  return s @ v + r

In [30]:
prediction = model(inputs)
print(prediction)

tf.Tensor(
[[ 42.23252422  89.86893941]
 [ 53.73203808 123.1888741 ]
 [ 55.86291319 162.2671552 ]
 [ 53.44610936  63.76250634]
 [ 44.33714179 134.39223425]
 [ 42.23252422  89.86893941]
 [ 53.73203808 123.1888741 ]
 [ 55.86291319 162.2671552 ]
 [ 53.44610936  63.76250634]
 [ 44.33714179 134.39223425]
 [ 42.23252422  89.86893941]
 [ 53.73203808 123.1888741 ]
 [ 55.86291319 162.2671552 ]
 [ 53.44610936  63.76250634]
 [ 44.33714179 134.39223425]], shape=(15, 2), dtype=float64)


In [31]:
def mse(t1,t2):
    return tf.reduce_mean(tf.square(t1 - t2))
print(mse(prediction,targets))

tf.Tensor(1204.6405476603315, shape=(), dtype=float64)


In [32]:
epochs = 40
for epoch_count in range(epochs):
    
    with tf.GradientTape(persistent=True) as t:
        current_loss = mse(targets, model(inputs))

    v1 = t.gradient(current_loss,v)
    r1 = t.gradient(current_loss,r)

    v.assign_sub(1e-4 * v1)
    r.assign_sub(1e-4 * r1)
        
    print(f" \n Epoch count: {epoch_count} \n Loss value: {current_loss.numpy()}")


 
 Epoch count: 0 
 Loss value: 1204.6405476603315
 
 Epoch count: 1 
 Loss value: 876.3337067465465
 
 Epoch count: 2 
 Loss value: 656.5819891177084
 
 Epoch count: 3 
 Loss value: 506.4915363394669
 
 Epoch count: 4 
 Loss value: 401.5161205677253
 
 Epoch count: 5 
 Loss value: 326.1116273696722
 
 Epoch count: 6 
 Loss value: 270.3886964694542
 
 Epoch count: 7 
 Loss value: 228.01579767623122
 
 Epoch count: 8 
 Loss value: 194.90492112431937
 
 Epoch count: 9 
 Loss value: 168.38717239388674
 
 Epoch count: 10 
 Loss value: 146.695117315411
 
 Epoch count: 11 
 Loss value: 128.63726253190615
 
 Epoch count: 12 
 Loss value: 113.3929410563068
 
 Epoch count: 13 
 Loss value: 100.38270312278853
 
 Epoch count: 14 
 Loss value: 89.18610112912629
 
 Epoch count: 15 
 Loss value: 79.48926299886202
 
 Epoch count: 16 
 Loss value: 71.05122289206392
 
 Epoch count: 17 
 Loss value: 63.68209332627914
 
 Epoch count: 18 
 Loss value: 57.22873901300545
 
 Epoch count: 19 
 Loss value: 51.